apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: external-secrets
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-secret
  data:
    - secretKey: DB_USER
      remoteRef:
        key: zenith-prod-mysql
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: zenith-prod-mysql
        property: DB_PASSWORD
    - secretKey: DB_URL
      remoteRef:
        key: zenith-prod-mysql
        property: DB_URL