apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-secret
  namespace: external-secrets
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: github-secret
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: zenith-prod-github
        property: GITHUB_TOKEN

