apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: external-secrets
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: redis-secret
  data:
    - secretKey: REDIS_AUTH_TOKEN
      remoteRef:
        key: zenith-prod-redis
        property: REDIS_AUTH_TOKEN
    - secretKey: REDIS_ENDPOINT
      remoteRef:
        key: zenith-prod-redis
        property: REDIS_ENDPOINT

